#!/usr/bin/env bash
# Rsync the LEC CRM working tree to EC2, generate .env, bring up the stack.
# Run from inside WSL: bash /tmp/deploy-to-ec2.sh

set -e
EIP=13.204.229.25
KEY=$HOME/.ssh/lec-aws.pem
LOCAL_REPO=$HOME/lec-crm
REMOTE_DIR=/opt/lec-crm

SSH="ssh -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=$HOME/.ssh/known_hosts -i $KEY"

echo "→ rsyncing repo to EC2 (excluding node_modules, .next, .env*)"
rsync -a --delete \
  --exclude='.git/objects/pack/*.pack' \
  --exclude='node_modules' \
  --exclude='.next' \
  --exclude='.env' \
  --exclude='.env.local' \
  --exclude='out' \
  --exclude='build' \
  --exclude='dist' \
  --exclude='coverage' \
  -e "$SSH" \
  "$LOCAL_REPO/" "ubuntu@$EIP:$REMOTE_DIR/"

echo "→ generating .env on EC2 (if missing) with strong random secrets"
$SSH ubuntu@$EIP "cd $REMOTE_DIR && bash -c '
if [ ! -f .env ]; then
  POSTGRES_PASSWORD=\$(openssl rand -base64 24 | tr -d \"=+/\" | cut -c1-24)
  AUTH_SECRET=\$(openssl rand -base64 32 | tr -d \"=+/\" | cut -c1-40)
  cat > .env <<EOF
# Generated by deploy script on \$(date)
POSTGRES_USER=lec
POSTGRES_PASSWORD=\$POSTGRES_PASSWORD
POSTGRES_DB=lec_crm

DOMAIN=:80
AUTH_SECRET=\$AUTH_SECRET
AUTH_URL=http://$EIP
AUTH_TRUST_HOST=true

WHATSAPP_PROVIDER=stub
RAZORPAY_PROVIDER=stub

TZ=Asia/Kolkata
NODE_ENV=production
SKIP_SEED=false
EOF
  chmod 600 .env
  echo \"  ✓ .env written\"
else
  echo \"  ✓ .env already exists (preserving)\"
fi
'"

echo "→ building + starting the stack (this takes 5-10 min the first time)"
$SSH ubuntu@$EIP "cd $REMOTE_DIR && sudo docker compose pull --ignore-pull-failures 2>&1 | tail -5 ; sudo docker compose up -d --build 2>&1 | tail -20"

echo ""
echo "→ container status"
$SSH ubuntu@$EIP "cd $REMOTE_DIR && sudo docker compose ps"

echo ""
echo "→ tailing app logs for 30s to confirm boot..."
$SSH ubuntu@$EIP "cd $REMOTE_DIR && timeout 30 sudo docker compose logs -f --tail=40 app 2>&1 || true"
